version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/koron/sqs-notify
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test all
          command: go test -v ./...

      - run:
          name: Build releases
          command: |
            make release-all
            mkdir -p /tmp/artifacts
            mv tmp/*.tar.gz /tmp/artifacts

      - store_artifacts:
          path: /tmp/artifacts
