name: Go

on: [push]

env:
  GO_VERSION: '>=1.23.0'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        - macos-latest
        - windows-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test ./...

    - run: go build

    - name: "Build: sqs-notify2"
      run: go build ./cmd/sqs-notify2

    - name: "Build: sqs-echo"
      run: go build ./cmd/sqs-echo

    - name: "Build: sqs-send"
      run: go build ./cmd/sqs-send

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
