name: Go

on: [push]

env:
  GO_VERSION: '>=1.23.0'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        - macos-latest
        - windows-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test ./...

    - name: Build all "main" packages
      shell: bash
      run: |
        root=$(go list -f '{{.ImportPath}}' .)
        for path in $(go list -f '{{if (eq .Name "main")}}{{.ImportPath}}{{end}}' ./... ) ; do
          dir=".${path#${root}}"
          printf "building %s\t(%s)\n" $(basename "$path") $dir
          ( cd "$dir" && go build )
        done

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
